website-updation
srm-kzilla/srmkzilla-net pull request #83
Opened 2023-08-02 19:12 UTC by utkarshini14

# Description

Updated the following:

### Landing page

- [x] remove what's new ke niche jo everything hai from the navbar 

![Screenshot 2023-08-03 000213](https://github.com/srm-kzilla/srmkzilla-net/assets/115221934/13da3c19-7035-4861-88c1-037b9cea6020)

### About us https://www.srmkzilla.net/about

- [x] get in touch with edi and events assoc and leads and update this pic

![image](https://github.com/srm-kzilla/srmkzilla-net/assets/115221934/3af8c546-d7ba-442c-9a5c-f3669ee6f7ac)

- [x] Update other pictures and content, make it more recent

### our services 

- [ ] ~~Update the testimonials and add new ones~~

- [x] Update the let's team up and add a cal.com link there instead 

- [x] Update the content of mozofest and mozohack
![image](https://github.com/srm-kzilla/srmkzilla-net/assets/115221934/9ae9bce7-6cd7-4fbd-8475-a4c47b913c62)

Fixes #82 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-08-03 05:40 UTC, shawshankkumar requested changes

2023-08-03 05:40 UTC, shawshankkumar commented on shared/components/services/collaborate.tsx
> +          <a href="https://cal.com/srmkzilla/hello" rel="noopener noreferrer">
target="_blank"

2023-08-04 13:08 UTC, shawshankkumar requested changes

2023-08-04 13:08 UTC, shawshankkumar commented on pages/about.tsx
> -              src="/images/mozofest.png"
remove mozofest.png from public if it is not being used elsewhere

2023-08-04 13:11 UTC, shawshankkumar commented
<img width="1792" alt="image" src="https://github.com/srm-kzilla/srmkzilla-net/assets/74819565/e16d179f-68ad-4ec6-bc73-e7f70e12509a">


 update photos here and content too

2023-08-04 13:12 UTC, shawshankkumar commented
issue galat linked hai, # and the number has to be together without any space

2023-08-04 13:12 UTC, shawshankkumar commented
#83  like this

2023-08-04 15:55 UTC, shawshankkumar commented
@utkarshini14 get these done by tonight, mark it ready for review, get it reviewed by me and one of the leads and let's get this merged.

2023-08-04 19:02 UTC, shawshankkumar approved these changes
LGTM! 🚀

2023-08-05 05:03 UTC, sm-sami approved these changes
LGTM! 🚀

2023-08-05 05:06 UTC, merged